spring.datasource.url=jdbc:postgresql://localhost:5432/VILLAFARMA_BD
spring.datasource.username=postgres
spring.datasource.password=B1Admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8484
jwt.secret=pvNkekZYq5GkAk!26$BSw$D4PKBwbbVn
jwt.expirationMs=86400000
logging.level.org.springframework.security=DEBUG
